### Appointment HTTP requests
#Base URL: http://localhost:3000/appointments
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzYwNTE4MzM0LCJleHAiOjE3NjA1MjE5MzR9.n85SFa4Z8A9Wu69GKzrVLWLjy4KOy9lhb_xtxfIM9_o
@baseUrl = http://localhost:3000
### List appointments
# Peticiones sin autenticación (token no requerido)
GET {{baseUrl}}/api/appointment/public
Accept: application/json

### Get appointment by id

# Peticiones con autenticación
GET {{baseUrl}}/api/appointment
Authorization: Bearer {{token}}
