
@token = 
@baseUrl = http://localhost:3000

# Listar todos los doctores
GET {{baseUrl}}/api/doctor/public
Accept: application/json

# Obtener un doctor por ID
GET http://localhost:3000/api/doctor/1
Content-Type: application/json

# Crear un nuevo doctor
POST http://localhost:3000/api/doctor
Content-Type: application/json

{
	"name": "Dr. Juan Pérez",
	"specialty": "Cardiología"
}

# Actualizar un doctor
PUT http://localhost:3000/api/doctor/1
Content-Type: application/json

{
	"name": "Dr. Juan Pérez",
	"specialty": "Neurología"
}

# Eliminar un doctor
DELETE http://localhost:3000/api/doctor/1
Content-Type: application/json

# Peticiones con autenticación

GET {{baseUrl}}/api/doctor
Authorization: Bearer {{token}}
