### PrescriptionDetail HTTP requests
# Base URL: http://localhost:3000/prescriptionDetails
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzYwNTA5MzA0LCJleHAiOjE3NjA1MTI5MDR9.Gpyq0iGd8qu7nPSpQ_pyVICJCRZSct4fXxUOn0mGjTI
@baseUrl = http://localhost:3000
### List prescription details
GET {{baseUrl}}/api/prescriptionDetail/public
Accept: application/json

### Peticiones con autenticación
GET {{baseUrl}}/api/prescriptionDetail
Authorization: Bearer {{token}}